---
- hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
  
    - name: Configure Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'

    - name: Create custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-{{ inventory_hostname[-1] }}"

    - name: Start Apache
      service:
        name: apache2
        state: started

- hosts: webservers
  become: yes
  tasks:
    - name: Stop Apache and remove index.html
      service:
        name: apache2
        state: stopped  # Ensure proper indentation here

    - name: Remove Apache
      apt:
        name: apache2
        state: absent

    - name: Delete index.html
      file:
        path: /var/www/html/index.html
        state: absent
